### ISSUE TITLE
Update info with Dr. Giddings' edits

### ISSUE THREAD

**Issue by ajkeith** [treypujats/COVID19#10]
Dr. Giddings: Can you (or the AFITeers) shoot me an editable file I can modify and shoot back?  (Some of it is minor error like saying “OCONUS installation” when only CONUS are included, some is insertion of just a little HAF/A9 linkage in the right places, some is putting some cautionary wording in the “overview” to pull users into some of the material that explains the calculations and projections.)

**Comment by galarcon0308** [comment]
Still need that file?
[CHAD Dashboard Edits.docx](https://github.com/treypujats/COVID19/files/4456185/CHAD.Dashboard.Edits.docx)

**Comment by tleonard6** [comment]
It's okay for now.  Dr. Giddings is actually editing a word doc right now.  I'll get back to you with the updates

**Comment by tleonard6** [comment]
First edits.  Inputs provided by Dr. Giddings.  I've read through, they seem appropriate, but take a look too to make sure they're okay.  I'll post the others as they come in.  Plan on updates to the public site to be done by 1145 (before the 1200).

[CHAD overview text.docx](https://github.com/treypujats/COVID19/files/4456441/CHAD.overview.text.docx)

**Comment by galarcon0308** [comment]
Awesome, we'll get on it!

**Comment by galarcon0308** [comment]
Edits done

**Comment by tleonard6** [comment]
More edits, Please read carefully, not a blanket accept with this one

[CHAD USER INPUTS text.docx](https://github.com/treypujats/COVID19/files/4456905/CHAD.USER.INPUTS.text.docx)
