### ISSUE TITLE
Recommendation: Change to version 0.2.3 and add beta tag

### ISSUE THREAD

**Issue by ajkeith** [treypujats/COVID19#11]
I think it's really good practice that the team is already tagging releases and posting the version number prominently on the tool. Great work!

I recommend changing to version 0.2.3 and having a beta tag (i.e. the title of the dashboard says Beta somewhere). We have two audiences: technical users and non-technical users. 

Non-technical users probably are not familiar with the details of versioning, so including a beta tag would help them understand that we haven't set up robust automatic testing yet and haven't had widespread usage in the "wild" yet. I totally agree with the team's focus so far on developing features for analysis at "the speed of relevance" and making code testing a lower priority - we just need to help our users understand how careful they need to be with the product and be clear about the testing status. 

For technical users, the version will be meaningful and a 1.0+ version implies at a minimum that there is continuous integration testing and an expectation of feature stability. For context, the Pandas package in python went to version 1.0 in Jan 2020 after 9 years of development. It was in widespread production use while still in the 0.X development cycle for many years.

**Comment by ajkeith** [comment]
@treypujats Great release notes btw

**Comment by galarcon0308** [comment]
Yeah that's a good point, we can do that.

**Comment by ajkeith** [comment]
What was the logic behind not including "beta" in the title?

**Comment by treypujats** [comment]
We can add beta, fixing that now

Sent from Mail for Windows 10
