### ISSUE TITLE
Add core project description

### ISSUE THREAD

**Issue by ajkeith** [treypujats/COVID19#12]
Since we are hoping to have more AFAC participation it would help them get started if we have a more complete project description. 

License: since this is hosted publicly we should be explicit about the license and distribution. I believe we can't hold a license since this is a government product - similar to the disclaimer we have when we publish papers? Either way I think the MIT license would be safe.

Contributing: Recommend using the same guidelines as the CONTRIBUTING.md at https://gitlab.devforce.disa.mil/A9-ADV/covid19/-/blob/master/CONTRIBUTING.md

**Comment by galarcon0308** [comment]
Is this something to throw in the overview or make a new popup for, or make a disclaimer on the bottom. We are new to this aspect so any help would be great on placement.

**Comment by galarcon0308** [comment]
I updated this on our github

**Comment by ajkeith** [comment]
Looks good - I made some minor edits and submitted a PR https://github.com/treypujats/COVID19/pull/13.
