### ISSUE TITLE
Feature: Add DTRA model

### ISSUE THREAD

**Issue by ajkeith** [treypujats/COVID19#14]
Add DTRA model to hurricane chart. Need to confirm that this data is not FOUO. This might be a good job for @mattburzenski?

Note: need to prioritize this with the other work.

**Comment by SlicedBadge** [comment]
The DTRA data looks like it is infection numbers; CHAD currently displays hospitalization numbers, right?

**Comment by tleonard6** [comment]
The goal is to include infections, hospitalizations, and deaths

**Comment by mattburzenski** [comment]
In their most recent slide deck, DTRA has hospitalizations on one of the "Model Calibration" slides. It looks like their just assuming a 25% hospitalization rate of those infected

**Comment by mattburzenski** [comment]
the hospitalization graph is the same as the reported cases graph, just scaled down a factor of 4

**Comment by mattburzenski** [comment]
Doesn't CHIME use a similar logic of saying X percentage of cases will be hospitalized?

**Comment by tleonard6** [comment]
@mattburzenski Yes, CHIME uses a set input.  We use 15%, 22%, and 27% as a min, avg, max percent of hospitalizations

**Comment by mattburzenski** [comment]
copy. Looks like those percentage bins can easily be applied to DTRA's output since they only model reported infections. the hospitalizations appear to be scaled after the fact

**Comment by galarcon0308** [comment]
I agree here, if they model infections we can apply proportions to get hospitalizations and deaths. It's what most other models are doing I believe. Do we know if they host their output somewhere or are willing to? Might make it easier to automate a daily grab

**Comment by tleonard6** [comment]
We just set up a weekly deliverable from DTRA to A9 of their model outputs.  I believe they will be posting on ADVANA in the future which would make it easier.

**Comment by Sleekery** [comment]
I know this isn't really the point, but I can make a video of the progressions. They are not interactive, but they might be cool. It'll take a couple hours of coding plus a day to render. Anybody want it and think it's worth doing?

**Comment by treypujats** [comment]
That would be cool to add, not sure how the rendering aspect would impact the website speed. If you can that would be great. @Sleekery

**Comment by Sleekery** [comment]
Not sure I explained it well. Basically, the videos would have to be created completely separate from the dashboard, and then you would have to embed the pre-made video wherever. It takes my code probably several hours to make a good looking animation.

**Comment by galarcon0308** [comment]
Maybe just a national map then? Probably be infeasible to get it for every county view

**Comment by mattburzenski** [comment]
hey guys what's the easiest way to get you guys these initial R scripts I'm working? I think I remember Andrews mentioning before that there are only a certain number of users that can push to this git channel?

**Comment by treypujats** [comment]
You are a contributor now

**Comment by mattburzenski** [comment]
DTRA model output is actually FOUO so I won't push it here. Will likely push to gitlab shortly.

**Comment by ajkeith** [comment]
This is on hold pending more coordination with DTRA.
