### ISSUE TITLE
Recommendation: Non-analyst Guard Rails

### ISSUE THREAD

**Issue by ajkeith** [treypujats/COVID19#18]
Now that the target audience is slightly different, I recommend that we put in more restrictions on the user interface, but I think it's worth discussing exactly how we want to do that. A few suggestions to get us started:

1. Restrict projections to 30 days out max. The lack of multi-peak models makes the 30+ day projections misleading.
2. Consider replace the social distancing slider with pre-built scenarios (similar to the approach in ADVANA).

**Comment by treypujats** [comment]
We have fixed the social distancing. We believe the way forward with with the projections days is to keep as a slider. The functionality of that is for the user to adjust their view on the graph and show where at that projection they expect to be.
