### ISSUE TITLE
Space Bases

### ISSUE THREAD

**Issue by tleonard6** [treypujats/COVID19#19]
Mr. Swallow requested that Space Bases be titled as such to reflect "DAF" nature of the tool vs Air Force specific tool.  It is important for strategic communication.  
Can you add"(USSF)" to the following installations? 
Buckley AFB, Colorado
Los Angeles AFB,California
Patrick AFB and Cape Canaveral AFS, FL
Peterson AFB, Colorado
Schriever AFB, Colorado
Vandenberg AFB, Ca

**Comment by treypujats** [comment]
Yes, I can go through those bases. I was also planning on sorting the base
selection by active duty, reserve and guard. Thoughts?

**Comment by weirj1** [comment]
Can we sort the summary tab as well?

**Comment by tleonard6** [comment]
@treypujats I think that's a good idea.  @weirj1 yes we'll sort. I had a urgent need for those results so it's not pretty yet.

**Comment by treypujats** [comment]
Done
