### ISSUE TITLE
Hospitalizations vs Cases in Projected Hospitalizations Comparison

### ISSUE THREAD

**Issue by ajkeith** [treypujats/COVID19#2]
Hey guys, the dashboard is looking great! 

I know you guys are moving really quickly and this is a very much in-development tool but I noticed what I think is a bug and wanted to note it here so I don't forget to tell you later. You may already be aware. 

CAO: 0900 6 Apr 2020
Run Dashboard (had to make a quick adjustment to the join by name for IHME from "location" to "location_name"...maybe this is causing it? I'm assuming the data source changed their schema at some point)
Wright Patt: Local Health Projections - Project Hospitalizations shows cases from SIR and hospitalizations from IHME?
JB Andrews: IHME predicts more hospitalizations than SIR does cases? 

This is just for your SA, feel free to close the issue.

**Comment by galarcon0308** [comment]
Changed to pulling the column index since they haven't changed their data structure yet. Thanks for the find!
