### ISSUE TITLE
Hospital Utilization

### ISSUE THREAD

**Issue by tleonard6** [treypujats/COVID19#23]
Need to turn off from the dashboard until we can reformulate it in a way that addresses or overcomes the concern presented in the zoom.

**Comment by galarcon0308** [comment]
On Local Health tab, hospital bed utilization and utilization change have been recalculated using county demographics and hospitalization rates for each demographic (along with the previous input of staffed beds and historic utilization rates). The hospitalization rates for demographics was taken from NYC cases from their department of health. NYC has the most cases (largest sample size), and most diverse city in this country. Therefore it seems more appropriate than any other place. I'll update the sources to reflect this along with the calculations

**Comment by galarcon0308** [comment]
For daily projections, we are still working on switching the charts to represent daily hospital utilization as opposed to cases.

**Comment by ajkeith** [comment]
There is a direct request from Mr. Swallow and Dr. Giddings to temporarily take off the Estimated Local Hospital Bed Utilization rectangle as soon as possible. 

This is a good discussion to have and I think you guys have a reasonable approach. That being said, this is a live product, so temporarily taking it down allows us to discuss at a more thoughtful pace.

**Comment by ajkeith** [comment]
Thanks - looks good for now.

**Comment by treypujats** [comment]
This has been fixed, working on it now to better reflect hospitalizations. We can reopen the issue if we see fit after after the adjustment is made.
