### ISSUE TITLE
Predicted Peak Projections Statistic not Changing 

### ISSUE THREAD

**Issue by clarencew0083** [treypujats/COVID19#25]
Selecting fatalities in the choose projected statistics radio button, does not update the predicted peak projections on the Local Health Projections tab. I don't know if this is intended but I imagine if a user chooses fatalities then the predicted peak fatalities should display for IHME and CHIME at the top of the Local Health Projections tab. Currently, the predicted peak hospitalizations given by the two models will always display.

**Comment by treypujats** [comment]
Working on that, as of now it’s not changing but it’s something we need to
add

**Comment by treypujats** [comment]
done
