### ISSUE TITLE
Match Projected Y-Axis Scales

### ISSUE THREAD

**Issue by ajkeith** [treypujats/COVID19#26]
From James Lotspeich, Lt Col, ACC/A6T:
It would be better from a presentation standpoint to match scales on the Y-axis between the CHIME and IHME models.  Without matching you risk non-technical viewers thinking models are within general agreement.

**Comment by galarcon0308** [comment]
This is an argument for getting rid of the individual plots and just leaving the overlays, as the overlay solves this problem. Thoughts?

**Comment by treypujats** [comment]
In some cases the IHME scale is not seen very well in comparison to CHIME,
so I personally think that two separate plots on their own scale  give a
visualization on how the curve looks, and the overlay matches the scales to
show how they compare

**Comment by treypujats** [comment]
Discussed. We believe the way forward is having separate plots and the Y-axis is the same on the overlay. That way one curve is not dominated by the other in the case that one predicts much higher hospitalizations.
