### ISSUE TITLE
Labels on Uncertainty Area

### ISSUE THREAD

**Issue by ajkeith** [treypujats/COVID19#27]
From Joseph Schmitt, A9:
What’s the uncertainty range? Might be important to label the range 5-95% range or something.

**Comment by ajkeith** [comment]
Dr. Giddings also had a similar comment. 

I think we should avoid words like "bound" or "maximum/minimum" since we have other projections that are outside the current bounds. 

From Trey Pujats to Everyone:  12:29 PM
The uncertainty is based on CDC planning factors for CHIME and 95%CI for IHME

I believe IHME prefers uncertainty interval to confidence interval. 

I suggest using the verbiage Upper and Lower estimate (or upper and lower 95% Uncertainty Interval, as appropriate).

**Comment by treypujats** [comment]
done
