### ISSUE TITLE
Detailed Documentation of Model Inputs

### ISSUE THREAD

**Issue by ajkeith** [treypujats/COVID19#29]
From Thomas Himes:
Are the detailed inputs to the IHME and CHIME models found somewhere in the tool?

**Comment by galarcon0308** [comment]
CHIME inputs will be provided as a page on the github. We can link to it. Don't want to overburden the dash with more technical stuff than needed. The IHME doesn't provide model inputs as far as I know, which is why it's difficult to replicate on your own.

**Comment by treypujats** [comment]
All parameters to CHIME are detailed. Parameters for IHME are not created by developers, rather they are pulled from IHME website specifically.
