### ISSUE TITLE
Add "Current As of" for each product

### ISSUE THREAD

**Issue by ajkeith** [treypujats/COVID19#31]
Add "current as of" for each plot or data table.

**Comment by treypujats** [comment]
We have placed that in the sidebar at the bottom for right now. Do you still want us to put it on every chart?

**Comment by ajkeith** [comment]
This is not a high priority, but having it in each chart is good practice. That way if people need to snip it for a chart it's right there and they are more likely to include. Also does IHME update daily?

**Comment by galarcon0308** [comment]
Yeah IHME typically updates daily

**Comment by galarcon0308** [comment]
This also might be solved in the report feature

**Comment by treypujats** [comment]
done
