### ISSUE TITLE
Feature: Change social distancing input to scenarios

### ISSUE THREAD

**Issue by ajkeith** [treypujats/COVID19#34]
Request from BRINCS: change social distancing slider to a checkbox interface for SC, NE, SD

**Comment by treypujats** [comment]
Can be done, thank you. Will work on that


Sent from Mail for Windows 10

From: Andrew Keith
Sent: Friday, April 10, 2020 12:20 PM
To: treypujats/COVID19
Cc: Subscribed
Subject: [treypujats/COVID19] Feature: Change social distancing input toscenarios (#34)

Request from BRINCS: change social distancing slider to a checkbox interface for SC, NE, SD

**Comment by tleonard6** [comment]
Just to clarify, want to select all combinations of the 3 just as described on the info page

**Comment by treypujats** [comment]
Correct, checkbox not select box
