### ISSUE TITLE
IHME_Model merge

### ISSUE THREAD

**Issue by jrlindell** [treypujats/COVID19#4]
this is the original code

IHME_Model <- merge(IHME_Model, StateList, by.x = "location", by.y = names(StateList)[1])

the problem i faced is that they seemed to have updated it to have location_name, so i wrote this code to combat this.

IHME_Model <- merge(IHME_Model, StateList, by.x = colnames(IHME_Model[grep('location', colnames(IHME_Model), fixed=FALSE)]), by.y = names(StateList)[1])

**Comment by treypujats** [comment]
And that’s working for you?

**Comment by jrlindell** [comment]
yes b/c it will look at "location_name" and the grep function finds a column that has "location" within the name and then uses that column

**Comment by treypujats** [comment]
Yeah, happy to throw that in there. You want me to add that or do you want
to push it? If you’re not completely up to date, I can do it

**Comment by jrlindell** [comment]
u got it. i stil dont understand github

**Comment by galarcon0308** [comment]
Good find! We pushed an update yesterday where by.x = names(IHME_Model)[2]

We might switch the code you posted above. They seem to be fickle on their variable names and file names, but their model output structure seems consistent over time. Where the location is always the second column.
