### ISSUE TITLE
Version 2.1

### ISSUE THREAD

**Issue by weirj1** [treypujats/COVID19#5]
Version 2.1 is not labeled as 2.1 in the header.  Need to change Ui.R to reflect version number.

**Comment by treypujats** [comment]
Fixed, thank you. Let me know if you see any other issues,


Sent from Mail for Windows 10

From: weirj1
Sent: Wednesday, April 8, 2020 11:45 AM
To: treypujats/COVID19
Cc: Subscribed
Subject: [treypujats/COVID19] Version 2.1 (#5)

Version 2.1 is not labeled as 2.1 in the header. Need to change Ui.R to reflect version number.
