### ISSUE TITLE
Dashboard page title (ui.R)

### ISSUE THREAD

**Issue by ltcarendt** [treypujats/COVID19#6]
Update ui.R, line 23, to correctly display page title:
dashboardPage(skin = "black", **title="COVID-19 Health Assessment Dashboard",**

**Comment by treypujats** [comment]
I have updated this in the ui.R, but I believe where this is supposed to be displayed is covered by the AFIT logo.

Sent from Mail for Windows 10

From: ltcarendt
Sent: Wednesday, April 8, 2020 11:55 AM
To: treypujats/COVID19
Cc: Subscribed
Subject: [treypujats/COVID19] Dashboard page title (ui.R) (#6)

Update ui.R, line 23, to correctly display page title:
dashboardPage(skin = "black", title="COVID-19 Health Assessment Dashboard",

**Comment by ltcarendt** [comment]
That’s fine.
Sorry for the confusion; this was just to address the title text that appears in the browser window tab; it’s not intended to replace AFIT logo for the dashboardHeader.
Without this change, the browser window tab title was the HTML string for the logo, “<div> <img src=...”

**Comment by treypujats** [comment]
Okay, thank you. This will be updated when we make the next publish today

Sent from Mail for Windows 10

**Comment by ltcarendt** [comment]
That’s fine; this wasn’t intended to replace the dashboardHeader, just the browser window/tab title text.
Without this change, the browser window/tab title text was the literal HTML string for the dashboardHeader, “< d iv > <i mg src = ...”.

**Comment by treypujats** [comment]
Thank you, we have just pushed an update to the website. Let us know if you see any more bugs or changes we should make.

**Comment by weirj1** [comment]
I see you are putting past data on the IHME and CHIME overlap chart. Why
not put past data on the individual IHME and CHIME charts?

**Comment by treypujats** [comment]
We are including past data in all projections, including the individual IHME and CHIME, we just did not label the line separately. We can do that if you think that would be more helpful

Sent from Mail for Windows 10

**Comment by weirj1** [comment]
Yes, the blue, black, brown on the overlay looks good.  I think blue, black
on IHME  and brown, black on CHIME would look good

**Comment by weirj1** [comment]
The national charts look good it would be good if local looked like
national
