### ISSUE TITLE
Current Data Line

### ISSUE THREAD

**Issue by weirj1** [treypujats/COVID19#7]
I hate to leave issues and not be able to help fix them.  I see the current data on national and on local overlay but I do not see current data on Local IHME and local CHIME.

**Comment by treypujats** [comment]
As in it is not loading for you? We will work to fix this


Sent from Mail for Windows 10

From: weirj1
Sent: Wednesday, April 8, 2020 1:36 PM
To: treypujats/COVID19
Cc: Subscribed
Subject: [treypujats/COVID19] Current Data Line (#7)

I hate to leave issues and not be able to help fix them. I see the current data on national and on local overlay but I do not see current data on Local IHME and local CHIME.

**Comment by weirj1** [comment]
yes. nothing in the legend and only one line

**Comment by treypujats** [comment]
Dr. Weir, we just updated the website. If you can, check it out and let me know if you see any issues we can fix.
