### ISSUE TITLE
County Plots & Downloadable Report

### ISSUE THREAD

**Issue by treypujats** [treypujats/COVID19#8]
@Auburngrads 

Sir could you help to fix the issues we have with county plots. Most counties are included, but some are not matching with the county fips codes. We also wish to extend the county plots to Alaska and Hawaii, but the current data set we are using does not seem to have those included.

The second item is downloading a report of the information in the app given the inputs you have selected. We have a download CSV file but have been struggling to download Rmd files. Please let us know if you can help.

**Comment by clarencew0083** [comment]
@treypujats 
I got the html report to output on my machine with no errors. I have pushed the minor code changes to the master.

**Comment by galarcon0308** [comment]
Report good, County plots still need. I am going to close this one and suggest we open one separately  for county plots.
